services:
  eldewrito:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "11774:11774/udp"
      - "11775:11775/tcp"
      - "11776:11776/tcp"
      - "11777:11777/tcp"
    volumes:
      - ./eldewrito:/game
      - ./scripts:/scripts
      - ./logs:/logs
      - ./eldewrito/data:/config
    working_dir: /game
    command: [ "sh", "../scripts/start.sh" ]
    cap_add:
      - SYS_PTRACE
    environment:
      - ED_CFG_VERSION=0.7.0
      - INSTANCE_ID=server1
